//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessTypes
{
    using System.Collections.Generic;
    
    public partial class PrestamoType
    {
        public PrestamoType()
        {
            this.DetallePago = new HashSet<DetallePagoType>();
            this.DetallePrestamo = new HashSet<DetallePrestamoType>();
        }
    
        public int PrestamoId { get; set; }
        public int ClienteId { get; set; }
        public decimal CantidadPrestada { get; set; }
        public decimal TasaInteres { get; set; }
        public System.DateTime FechaPrestamo { get; set; }
        public string Estado { get; set; }
    
        public virtual ClienteType Cliente { get; set; }
        
        public virtual ICollection<DetallePagoType> DetallePago { get; set; }
        
        public virtual ICollection<DetallePrestamoType> DetallePrestamo { get; set; }
    }
}
