//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_PRESTAMO
    {
        public int DETALLE_PRESTAMO_ID { get; set; }
        public int PRESTAMO_ID { get; set; }
        public decimal MOVIMIENTO { get; set; }
        public int TIPO_MOVIMIENTO_ID { get; set; }
        public Nullable<int> DETALLE_PAGO_ID { get; set; }
        public string COMENTARIO { get; set; }
        public System.DateTime FECHA { get; set; }
    
        public virtual DETALLE_PAGO DETALLE_PAGO { get; set; }
        public virtual PRESTAMO PRESTAMO { get; set; }
        public virtual TIPO_MOVIMIENTO TIPO_MOVIMIENTO { get; set; }
    }
}
