//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SPPEntities : DbContext
    {
        public SPPEntities()
            : base("name=SPPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIENTE> CLIENTEs { get; set; }
        public virtual DbSet<DETALLE_PAGO> DETALLE_PAGO { get; set; }
        public virtual DbSet<DETALLE_PRESTAMO> DETALLE_PRESTAMO { get; set; }
        public virtual DbSet<PAGO> PAGOes { get; set; }
        public virtual DbSet<PRESTAMO> PRESTAMOes { get; set; }
        public virtual DbSet<TIPO_MOVIMIENTO> TIPO_MOVIMIENTO { get; set; }
    }
}
